version: "3.9"
services:
  app:
    build: ./app
    environment:
      OTEL_SERVICE_NAME: orders-service
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4317
      OTEL_TRACES_EXPORTER: otlp
      OTEL_METRICS_EXPORTER: otlp
      OTEL_LOGS_EXPORTER: otlp
      OTEL_RESOURCE_ATTRIBUTES: deployment.environment=dev
    ports: ["8080:8080"]
    depends_on: [otel-collector]

  otel-collector:
    image: otel/opentelemetry-collector:0.103.1
    command: ["--config=/etc/otel/config.yaml"]
    volumes:
      - ./otel-collector/config.yaml:/etc/otel/config.yaml:ro
    ports: ["4317:4317","9464:9464","8888:8888"]

  prometheus:
    image: prom/prometheus:v2.55.1
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports: ["9090:9090"]
    depends_on: [otel-collector]

  loki:
    image: grafana/loki:2.9.7
    command: -config.file=/etc/loki/local-config.yaml
    ports: ["3100:3100"]

  tempo:
    image: grafana/tempo:2.5.0
    command: [ "-config.file=/etc/tempo.yaml" ]
    ports: ["3200:3200"]

  grafana:
    image: grafana/grafana:11.2.2
    environment: [GF_SECURITY_ADMIN_PASSWORD=admin]
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
    ports: ["3000:3000"]
    depends_on: [prometheus,loki,tempo]
